### ISSUE TITLE
will your DSDT work for any Asus X99 Deluxe II

### ISSUE THREAD

**Issue by RiggsUS** [Toooorch/X99-Deluxe-II#1]
will your DSDT work for any Asus X99 Deluxe II (USA)
Motherboard: Asus X99 Deluxe II
Ram: SK Hynix HMA451U6AFR8N-TF 4GB x4 16Gb ram 
CPU: I7 6800K running OC at 4200Ghz
GPU: GXT1080 
Storage: PM951 NVMe SAMSUNG 256GB
PSU: CoolMax ZU-1000B.
I plan on adding the ThunderBolt card that came in the box later
everything on the board is stock Bluetooth, WIFI etc.

**Comment by Toooorch** [comment]
@RiggsUS 
Don't use the same DSDT because every setup is different, you have to generate your own in order to make it work correctly. 

Try to contact this guy, use his "send me.app" and then share the files with him.
https://www.insanelymac.com/forum/profile/557433-mald0n/

Thunderbolt card will not work. There is no report it works under MacOS.
